### ISSUE TITLE
No windows app anymore?

### ISSUE THREAD

**Issue by N72826** [fashni/lrc-generator#6]
Hey so, firstly, thanks for making this. I can't download the musixmatch app on the windows store anymore so I'm not sure how I am supposed to get a token. Thanks in advanced.

**Comment by totallynotadi** [comment]
There is no token needed necessarily from the user (you), a token is already present in the code. Just clone this repository and execute commands as per in the readme and everything should work. Let us know here if you have any problems and close this issue if everything goes well. Thanks!

**Comment by N72826** [comment]
thank you so much. that was all.
